name: merge-main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  merge-main:
    runs-on: [valstro-runner, node20, linux-medium]
    timeout-minutes: 15

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          # Defaults to the user or organization that owns the workflow file
          scope: "@valstro"
          registry-url: "https://npm.pkg.github.com"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Creating Release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest

      - name: Build Package
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build

      - name: Publish Package (GitHub Package Registry)
        if: ${{ steps.release.outputs.releases_created }}
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

      - name: Publish Package (NPM Registry)
        if: ${{ steps.release.outputs.releases_created }}
        run: npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: false