name: pull-request-main

on:
  pull_request_target:  # Runs in context of base branch
    branches: [main]

jobs:
  # when in branches, if multiple runs exist and are active, cancel all but most recent run
  cancel-previous-runs:
    runs-on: ubuntu-latest
    # Only run for trusted repos
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

  pr-main:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Don't persist credentials
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          # Defaults to the user or organization that owns the workflow file
          scope: "@valstro"
          registry-url: "https://npm.pkg.github.com"
          cache: npm

      - name: Install Dependencies (Safe Mode)
        run: |
          # Install without running scripts for security
          npm ci --ignore-scripts
          
      - name: Run Tests (Trusted Repos Only)
        # Only run tests for trusted repos to prevent arbitrary code execution
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: npm test

      - name: Test Build
        run: npm run build

    # Skip if from fork
    if: github.event.pull_request.head.repo.full_name == github.repository