name: pull-request-main

on:
  pull_request:
    branches:
      - main

jobs:
  # when in branches, if multiple runs exist and are active, cancel all but most recent run
  cancel-previous-runs:
    runs-on: [valstro-runner, node20, linux-medium]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

  pr-main:
    runs-on: [valstro-runner, node20, linux-medium]
    timeout-minutes: 15
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          # Defaults to the user or organization that owns the workflow file
          scope: "@valstro"
          registry-url: "https://npm.pkg.github.com"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Test Build
        run: npm run build

      # TODO: Doesn't work due to IP restrictions on repo
      # - name: Verify Release (if release PR)
      #   if: startsWith(github.head_ref, 'release-please--branches--main')
      #   run: npm run release-dry-run
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Test Publish (if release PR)
        if: startsWith(github.head_ref, 'release-please--branches--main')
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}